services:
  - type: web
    name: aurafinance-backend
    env: node
    branch: main
    root: backend
    plan: free
    buildCommand: |
      cd ../aura-finance
      export NEXT_PUBLIC_API_URL=''
      npm ci
      npm run build
      cp -r out ../backend/public
      cd ../backend
      npm install
    startCommand: cd backend && npm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: "5000"
